# Generated by Django 5.2.1 on 2025-06-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.ImageField(upload_to='brest'),
        ),
    ]
