# Generated by Django 5.2.1 on 2025-06-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='status',
            field=models.CharField(choices=[('exist', 'exist'), ('none', 'none')], default='exist', max_length=20),
        ),
    ]
