# Generated by Django 5.2.1 on 2025-06-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.ImageField(upload_to='restaurant front'),
        ),
    ]
