# Generated by Django 5.2.1 on 2025-06-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant front'),
        ),
    ]
