# Generated by Django 5.2.1 on 2025-06-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_rating_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(blank=True, choices=[('dessert', 'dessert'), ('Seefood', 'Seefood'), ('spicy', 'spicy'), ('healthyfood', 'healthyfood')], null=True),
        ),
    ]
